# action.yml
name: Github action for bookdown
description: Renders pdf, tex or html documents out of rmarkdown files
author: Luis Chaves (Forked by Christian Kruse)
inputs:
  input_file:
    description: input rmarkdown file (.Rmd)
    required: true
  output_format:
    description: format of output document - pdf, html or tex
    required: true
    default: pdf
outputs:
  output_file: 
    description: Output document defaults as the name of the rmarkdown file with the output format
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input_file }}
branding:
  icon: book
  color: green
